// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jraptors.bibliosoft2.domain;

import com.jraptors.bibliosoft2.domain.ContactInfo;
import com.jraptors.bibliosoft2.domain.ContactInfoDataOnDemand;
import com.jraptors.bibliosoft2.domain.ContactInfoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactInfoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactInfoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactInfoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContactInfoIntegrationTest: @Transactional;
    
    @Autowired
    ContactInfoDataOnDemand ContactInfoIntegrationTest.dod;
    
    @Test
    public void ContactInfoIntegrationTest.testCountContactInfoes() {
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", dod.getRandomContactInfo());
        long count = ContactInfo.countContactInfoes();
        Assert.assertTrue("Counter for 'ContactInfo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactInfoIntegrationTest.testFindContactInfo() {
        ContactInfo obj = dod.getRandomContactInfo();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to provide an identifier", id);
        obj = ContactInfo.findContactInfo(id);
        Assert.assertNotNull("Find method for 'ContactInfo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ContactInfo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactInfoIntegrationTest.testFindAllContactInfoes() {
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", dod.getRandomContactInfo());
        long count = ContactInfo.countContactInfoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ContactInfo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ContactInfo> result = ContactInfo.findAllContactInfoes();
        Assert.assertNotNull("Find all method for 'ContactInfo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ContactInfo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactInfoIntegrationTest.testFindContactInfoEntries() {
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", dod.getRandomContactInfo());
        long count = ContactInfo.countContactInfoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ContactInfo> result = ContactInfo.findContactInfoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ContactInfo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ContactInfo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactInfoIntegrationTest.testFlush() {
        ContactInfo obj = dod.getRandomContactInfo();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to provide an identifier", id);
        obj = ContactInfo.findContactInfo(id);
        Assert.assertNotNull("Find method for 'ContactInfo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContactInfo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ContactInfo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactInfoIntegrationTest.testMergeUpdate() {
        ContactInfo obj = dod.getRandomContactInfo();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to provide an identifier", id);
        obj = ContactInfo.findContactInfo(id);
        boolean modified =  dod.modifyContactInfo(obj);
        Integer currentVersion = obj.getVersion();
        ContactInfo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ContactInfo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactInfoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", dod.getRandomContactInfo());
        ContactInfo obj = dod.getNewTransientContactInfo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ContactInfo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ContactInfo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactInfoIntegrationTest.testRemove() {
        ContactInfo obj = dod.getRandomContactInfo();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactInfo' failed to provide an identifier", id);
        obj = ContactInfo.findContactInfo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ContactInfo' with identifier '" + id + "'", ContactInfo.findContactInfo(id));
    }
    
}
