// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jraptors.bibliosoft2.domain;

import com.jraptors.bibliosoft2.domain.Location;
import com.jraptors.bibliosoft2.domain.LocationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LocationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LocationDataOnDemand: @Component;
    
    private Random LocationDataOnDemand.rnd = new SecureRandom();
    
    private List<Location> LocationDataOnDemand.data;
    
    public Location LocationDataOnDemand.getNewTransientLocation(int index) {
        Location obj = new Location();
        setAditionalinfo(obj, index);
        setCity(obj, index);
        setCountry(obj, index);
        setFloor(obj, index);
        setFloornumber(obj, index);
        setLocationname(obj, index);
        setPostalcode(obj, index);
        return obj;
    }
    
    public void LocationDataOnDemand.setAditionalinfo(Location obj, int index) {
        String aditionalinfo = "aditionalinfo_" + index;
        obj.setAditionalinfo(aditionalinfo);
    }
    
    public void LocationDataOnDemand.setCity(Location obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void LocationDataOnDemand.setCountry(Location obj, int index) {
        String country = "country_" + index;
        obj.setCountry(country);
    }
    
    public void LocationDataOnDemand.setFloor(Location obj, int index) {
        String floor = "floor_" + index;
        obj.setFloor(floor);
    }
    
    public void LocationDataOnDemand.setFloornumber(Location obj, int index) {
        String floornumber = "floornumber_" + index;
        obj.setFloornumber(floornumber);
    }
    
    public void LocationDataOnDemand.setLocationname(Location obj, int index) {
        String locationname = "locationname_" + index;
        obj.setLocationname(locationname);
    }
    
    public void LocationDataOnDemand.setPostalcode(Location obj, int index) {
        String postalcode = "postalcode_" + index;
        obj.setPostalcode(postalcode);
    }
    
    public Location LocationDataOnDemand.getSpecificLocation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Location obj = data.get(index);
        Long id = obj.getId();
        return Location.findLocation(id);
    }
    
    public Location LocationDataOnDemand.getRandomLocation() {
        init();
        Location obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Location.findLocation(id);
    }
    
    public boolean LocationDataOnDemand.modifyLocation(Location obj) {
        return false;
    }
    
    public void LocationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Location.findLocationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Location' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Location>();
        for (int i = 0; i < 10; i++) {
            Location obj = getNewTransientLocation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
