// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jraptors.bibliosoft2.domain;

import com.jraptors.bibliosoft2.domain.PlacementDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlacementDataOnDemand_Roo_Configurable {
    
    declare @type: PlacementDataOnDemand: @Configurable;
    
}
