// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jraptors.bibliosoft2.domain;

import com.jraptors.bibliosoft2.domain.Placement;
import com.jraptors.bibliosoft2.domain.PlacementDataOnDemand;
import com.jraptors.bibliosoft2.domain.PlacementIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlacementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlacementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlacementIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PlacementIntegrationTest: @Transactional;
    
    @Autowired
    PlacementDataOnDemand PlacementIntegrationTest.dod;
    
    @Test
    public void PlacementIntegrationTest.testCountPlacements() {
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", dod.getRandomPlacement());
        long count = Placement.countPlacements();
        Assert.assertTrue("Counter for 'Placement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlacementIntegrationTest.testFindPlacement() {
        Placement obj = dod.getRandomPlacement();
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Placement' failed to provide an identifier", id);
        obj = Placement.findPlacement(id);
        Assert.assertNotNull("Find method for 'Placement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Placement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlacementIntegrationTest.testFindAllPlacements() {
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", dod.getRandomPlacement());
        long count = Placement.countPlacements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Placement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Placement> result = Placement.findAllPlacements();
        Assert.assertNotNull("Find all method for 'Placement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Placement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlacementIntegrationTest.testFindPlacementEntries() {
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", dod.getRandomPlacement());
        long count = Placement.countPlacements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Placement> result = Placement.findPlacementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Placement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Placement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlacementIntegrationTest.testFlush() {
        Placement obj = dod.getRandomPlacement();
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Placement' failed to provide an identifier", id);
        obj = Placement.findPlacement(id);
        Assert.assertNotNull("Find method for 'Placement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPlacement(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Placement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlacementIntegrationTest.testMergeUpdate() {
        Placement obj = dod.getRandomPlacement();
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Placement' failed to provide an identifier", id);
        obj = Placement.findPlacement(id);
        boolean modified =  dod.modifyPlacement(obj);
        Integer currentVersion = obj.getVersion();
        Placement merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Placement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlacementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", dod.getRandomPlacement());
        Placement obj = dod.getNewTransientPlacement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Placement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Placement' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Placement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlacementIntegrationTest.testRemove() {
        Placement obj = dod.getRandomPlacement();
        Assert.assertNotNull("Data on demand for 'Placement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Placement' failed to provide an identifier", id);
        obj = Placement.findPlacement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Placement' with identifier '" + id + "'", Placement.findPlacement(id));
    }
    
}
