// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jraptors.bibliosoft2.domain;

import com.jraptors.bibliosoft2.domain.Placement;
import com.jraptors.bibliosoft2.domain.PlacementDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PlacementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PlacementDataOnDemand: @Component;
    
    private Random PlacementDataOnDemand.rnd = new SecureRandom();
    
    private List<Placement> PlacementDataOnDemand.data;
    
    public Placement PlacementDataOnDemand.getNewTransientPlacement(int index) {
        Placement obj = new Placement();
        setBookcase(obj, index);
        setShelve(obj, index);
        return obj;
    }
    
    public void PlacementDataOnDemand.setBookcase(Placement obj, int index) {
        String bookcase = "bookcase_" + index;
        obj.setBookcase(bookcase);
    }
    
    public void PlacementDataOnDemand.setShelve(Placement obj, int index) {
        String shelve = "shelve_" + index;
        obj.setShelve(shelve);
    }
    
    public Placement PlacementDataOnDemand.getSpecificPlacement(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Placement obj = data.get(index);
        Long id = obj.getId();
        return Placement.findPlacement(id);
    }
    
    public Placement PlacementDataOnDemand.getRandomPlacement() {
        init();
        Placement obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Placement.findPlacement(id);
    }
    
    public boolean PlacementDataOnDemand.modifyPlacement(Placement obj) {
        return false;
    }
    
    public void PlacementDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Placement.findPlacementEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Placement' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Placement>();
        for (int i = 0; i < 10; i++) {
            Placement obj = getNewTransientPlacement(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
